# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crach_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_hash', models.CharField(max_length=128)),
                ('crash_dump', models.FileField(upload_to=b'')),
                ('input_file', models.FileField(upload_to=b'')),
                ('report_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuzz_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_ip', models.GenericIPAddressField()),
                ('last_connection_time', models.DateTimeField(auto_now_add=True)),
                ('working_status', models.BooleanField(default=False)),
                ('server_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='crach_info',
            name='fuzz_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Fuzz_server'),
        ),
    ]
