# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuzz_server',
            old_name='server_ip',
            new_name='fuzz_ip',
        ),
        migrations.RenameField(
            model_name='fuzz_server',
            old_name='server_name',
            new_name='fuzz_target',
        ),
        migrations.RemoveField(
            model_name='fuzz_server',
            name='server_on',
        ),
        migrations.AddField(
            model_name='fuzz_server',
            name='fuzz_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuzz_server',
            name='fuzz_version',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
