# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20170721_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzz_server',
            name='last_connection_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 15, 47, 26, 639000)),
        ),
    ]
