# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170721_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RenameModel(
            old_name='Crach_info',
            new_name='Crash_info',
        ),
        migrations.RenameField(
            model_name='crash_info',
            old_name='input_file',
            new_name='input_data',
        ),
        migrations.AlterField(
            model_name='fuzz_server',
            name='last_connection_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
