# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170724_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash_info',
            name='crash_dump',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='crash_info',
            name='input_data',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='file',
            field=models.FileField(upload_to='documens/%Y/%m/%d'),
        ),
    ]
